login: &login
  username: hnl
  password: test44

# This line is not compatible with the gem 'taps' used to sync the dataabse with heroku
<%= file = File.join(Rails.root, "config", "dblogin.yml")
    IO.read(file) if File.exist?(file) %>

development:
  adapter: postgresql
  encoding: unicode
  database: oakland_answers_dev
  username: oakland_answers
  host: localhost

test:
  adapter: postgresql
  database: oakland_answers_test

production:
  adapter: postgresql
  encoding: unicode
  database: oakland_answers_production
  host: localhost
  pool: 5
  timeout: 5000
  <<: *login
